(source gnu)
(source org)
(source melpa)
(source marmalade)

(depends-on "git-commit-mode")
(depends-on "git-gutter")
(depends-on "git-gutter-fringe")
(depends-on "git-rebase-mode")
(depends-on "magit")
