(source gnu)
(source org)
(source melpa)
(source marmalade)

(depends-on "git-commit-mode")
(depends-on "git-gutter")
(depends-on "git-gutter-fringe")
(depends-on "git-rebase-mode")
(depends-on "git-timemachine")
(depends-on "magit")
(depends-on "s")
(depends-on "f")
(depends-on "ace-jump-mode")
(depends-on "pallet")

